// species.js
// Profiler for vanlige norske fiskearter. Verdiene er destillert praktisk +
// teoretisk fiskekunnskap, og brukes av anbefalingsmotoren til scoring.
//
//  - water:       'fresh' | 'salt'
//  - tempOpt:     [min,max] vanntemp (°C) der arten er mest aktiv/eter best
//  - tempActive:  [min,max] ytre grenser der arten i praksis hugger
//  - lightPref:   foretrukket lys ('low' = demring/skumring/overskyet, 'bright', 'any')
//  - depthBias:   typisk standplass ('shallow','mid','deep') – flyttes av temp i motoren
//  - lures:       agntyper som passer, med vekt (0-1) for hvor godt de passer arten
//  - sizeRange:   anbefalt agnvekt i gram [min,max]
//  - season:      måneder (1-12) der fisket typisk er best
//  - notes:       kort praktisk tips
export const SPECIES = {
  gjedde: {
    id: 'gjedde',
    name: 'Gjedde',
    nameEn: 'Northern pike',
    water: 'fresh',
    tempOpt: [12, 18],
    tempActive: [4, 24],
    lightPref: 'low',
    depthBias: 'shallow',
    lures: { jerkbait: 1.0, wobbler: 0.9, spinner: 0.85, spoon: 0.8, softbait: 0.85, topwater: 0.6 },
    sizeRange: [15, 80],
    season: [4, 5, 6, 9, 10, 11],
    notes: 'Standplass-jeger ved vegetasjon og kanter. Stort agn = stor gjedde. Sakte tak når vannet er kaldt.',
  },
  abbor: {
    id: 'abbor',
    name: 'Abbor',
    nameEn: 'Perch',
    water: 'fresh',
    tempOpt: [12, 20],
    tempActive: [4, 24],
    lightPref: 'bright',
    depthBias: 'mid',
    lures: { softbait: 1.0, spinner: 0.85, wobbler: 0.7, spoon: 0.6, jerkbait: 0.4 },
    sizeRange: [3, 15],
    season: [5, 6, 7, 8, 9, 10],
    notes: 'Stimfisk – finn én, finn flere. Liker små agn og jigging nær bunn. Aktiv i dagslys.',
  },
  orret: {
    id: 'orret',
    name: 'Ørret (innsjø/elv)',
    nameEn: 'Brown trout',
    water: 'fresh',
    tempOpt: [9, 16],
    tempActive: [2, 19],
    lightPref: 'low',
    depthBias: 'mid',
    lures: { spinner: 0.95, spoon: 0.9, fly: 0.9, wobbler: 0.7, softbait: 0.5 },
    sizeRange: [3, 18],
    season: [5, 6, 7, 8, 9],
    notes: 'Sky i klart vann – fisk fint og naturlig. Insektsklekkinger i demring gir hektisk overflatefiske.',
  },
  roye: {
    id: 'roye',
    name: 'Røye',
    nameEn: 'Arctic char',
    water: 'fresh',
    tempOpt: [4, 12],
    tempActive: [1, 16],
    lightPref: 'low',
    depthBias: 'deep',
    lures: { spoon: 0.95, spinner: 0.85, fly: 0.8, softbait: 0.6 },
    sizeRange: [3, 20],
    season: [6, 7, 8, 9],
    notes: 'Kaldtvannsfisk som ofte står dypt. Små, blanke skjesluk og rød/rosa innslag er en klassiker.',
  },
  harr: {
    id: 'harr',
    name: 'Harr',
    nameEn: 'Grayling',
    water: 'fresh',
    tempOpt: [8, 16],
    tempActive: [3, 18],
    lightPref: 'low',
    depthBias: 'mid',
    lures: { fly: 1.0, spinner: 0.7, softbait: 0.4 },
    sizeRange: [2, 8],
    season: [6, 7, 8, 9],
    notes: 'Insektseter i strømmende vann. Tørrflue/nymfe over standplassene er førstevalget.',
  },
  laks: {
    id: 'laks',
    name: 'Laks',
    nameEn: 'Atlantic salmon',
    water: 'fresh',
    tempOpt: [8, 14],
    tempActive: [4, 18],
    lightPref: 'low',
    depthBias: 'mid',
    lures: { fly: 0.95, spoon: 0.9, wobbler: 0.8, spinner: 0.8 },
    sizeRange: [10, 35],
    season: [6, 7, 8],
    notes: 'Hugger reaksjon, ikke sult, i elva. Tidlig morgen og kveld med litt vannføring er beste vindu.',
  },
  sjoorret: {
    id: 'sjoorret',
    name: 'Sjøørret',
    nameEn: 'Sea trout',
    water: 'salt',
    tempOpt: [6, 14],
    tempActive: [2, 17],
    lightPref: 'low',
    depthBias: 'shallow',
    lures: { spoon: 0.95, fly: 0.9, wobbler: 0.85, spinner: 0.75 },
    sizeRange: [10, 28],
    season: [3, 4, 5, 6, 9, 10, 11],
    notes: 'Kystjeger på grunna. Demring, skumring og litt sjø gir best sjanse. Vinterstøinger tar sakte agn.',
  },
  torsk: {
    id: 'torsk',
    name: 'Torsk',
    nameEn: 'Atlantic cod',
    water: 'salt',
    tempOpt: [4, 9],
    tempActive: [1, 14],
    lightPref: 'any',
    depthBias: 'deep',
    lures: { pirk: 1.0, softbait: 0.9, shrimp: 0.7, spoon: 0.5 },
    sizeRange: [60, 300],
    season: [1, 2, 3, 4, 11, 12],
    notes: 'Bunnfisk over rev og kanter. Pilk vertikalt og la agnet banke bunn. Kommer grunnere i kaldt vann.',
  },
  sei: {
    id: 'sei',
    name: 'Sei',
    nameEn: 'Saithe',
    water: 'salt',
    tempOpt: [6, 12],
    tempActive: [3, 16],
    lightPref: 'any',
    depthBias: 'mid',
    lures: { pirk: 0.95, softbait: 0.85, spoon: 0.7, shrimp: 0.5 },
    sizeRange: [40, 200],
    season: [5, 6, 7, 8, 9, 10],
    notes: 'Pelagisk og rasende kampsterk. Står ofte i frie vannmasser – tell agnet ned til riktig sjikt.',
  },
  makrell: {
    id: 'makrell',
    name: 'Makrell',
    nameEn: 'Mackerel',
    water: 'salt',
    tempOpt: [12, 18],
    tempActive: [9, 22],
    lightPref: 'bright',
    depthBias: 'shallow',
    lures: { spoon: 0.9, pirk: 0.85, spinner: 0.7, softbait: 0.6 },
    sizeRange: [10, 60],
    season: [6, 7, 8, 9],
    notes: 'Sommergjest i stim nær overflaten. Rask innspinning av blanke agn – let etter måkene og overflateaktivitet.',
  },
  lyr: {
    id: 'lyr',
    name: 'Lyr',
    nameEn: 'Pollack',
    water: 'salt',
    tempOpt: [8, 14],
    tempActive: [4, 18],
    lightPref: 'low',
    depthBias: 'mid',
    lures: { softbait: 0.95, pirk: 0.8, wobbler: 0.7, spoon: 0.6 },
    sizeRange: [30, 150],
    season: [5, 6, 7, 8, 9, 10],
    notes: 'Står ved tareskog og rev. Mykt agn fisket langs strukturen i demring er dødelig.',
  },
  hvitting: {
    id: 'hvitting',
    name: 'Hvitting',
    nameEn: 'Whiting',
    water: 'salt',
    tempOpt: [6, 12],
    tempActive: [2, 15],
    lightPref: 'low',
    depthBias: 'deep',
    lures: { shrimp: 0.9, softbait: 0.8, pirk: 0.6 },
    sizeRange: [20, 80],
    season: [9, 10, 11, 12, 1],
    notes: 'Bunnnær åtseleter, mest aktiv i mørke timer. Små naturlige agn nær bunn.',
  },
};

export function listSpecies() {
  return Object.values(SPECIES).map((s) => ({
    id: s.id,
    name: s.name,
    nameEn: s.nameEn,
    water: s.water,
    season: s.season,
    notes: s.notes,
  }));
}
